"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1500
format = '[╭─ ](fg:#B8C0DB)$directory$git_branch$git_status $fill$cmd_duration$nodejs$bun$c$rust$golang$php$java$kotlin$haskell$python$perl$lua$package$docker_context$conda$time$line_break[╰─](fg:#B8C0DB)$character'

[fill]
symbol = '·'
style = 'fg:#B8C0DB'

[time]
disabled = false
format = ' \[[$time](fg:#B8C0DB)\]'
time_format = '%H:%M:%S'

[directory]
style = "bold fg:#89B4FA"
format = '\[[$path]($style)\]'
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…"

[git_branch]
style = "fg:#f9e2af"
format = ' \[[$branch]($style)\]'

[git_status]
style = "fg:#f38ba8"
format = '( \[[$all_status$ahead_behind]($style)\])'

[line_break]
disabled = false

[package]
disabled = false
symbol = "󰏗 "
style = "fg:#fab387"
format = ' \[[$symbol$version]($style)\]'

[character]
disabled = false
success_symbol = '[❯](bold fg:#B8C0DB)'
error_symbol = '[❯](bold fg:#f38ba8)'

[cmd_duration]
show_milliseconds = false
format = ' \[[$duration]($style)\]'
style = "bold fg:#B8C0DB"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[nodejs]
symbol = ""
style = "fg:#a6e3a1"
format = ' \[[$symbol $version]($style)\]'

[bun]
symbol = ""
style = "fg:#f9e2af"
format = ' \[[$symbol $version]($style)\]'

[c]
symbol = ""
style = "fg:#a6adc8"
format = ' \[[$symbol $version]($style)\]'

[rust]
symbol = ""
style = "fg:#fab387"
format = ' \[[$symbol $version]($style)\]'

[golang]
symbol = ""
style = "fg:#94e2d5"
format = ' \[[$symbol $version]($style)\]'

[php]
symbol = ""
style = "fg:#cba6f7"
format = ' \[[$symbol $version]($style)\]'

[java]
symbol = ""
style = "fg:#eba0ac"
format = ' \[[$symbol $version]($style)\]'

[kotlin]
symbol = ""
style = "fg:#f5c2e7"
format = ' \[[$symbol $version]($style)\]'

[haskell]
symbol = ""
style = "fg:#b4befe"
format = ' \[[$symbol $version]($style)\]'

[python]
symbol = ""
style = "fg:#74c7ec"
format = ' \[[$symbol( $version)( #$virtualenv)]($style)\]'

[docker_context]
symbol = ""
style = "fg:#89b4fa"
format = ' \[[$symbol $context]($style)\]'


[perl]
symbol = ""
style = "fg:#89b4fa"
format = ' \[[$symbol $version]($style)\]'

[conda]
symbol = ""
style = "fg:#94e2d5"
format = ' \[[$symbol $environment]($style)\]'
ignore_base = false

[lua]
symbol = ""
style = "fg:#89dceb"
format = ' \[[$symbol $version]($style)\]'
