[username]
show_always = true
style_user = "fg:#8AADF5"
format = "[ @$user ]($style)"

[directory]
format = "[$path ]($style)"
truncation_length = 6
truncate_to_repo = false
truncation_symbol = "~/"

[git_branch]
style = "fg:yellow"

[git_status]
style = "fg:red"
format = "[$all_status$ahead_behind ]($style)"

[line_break]
disabled = true

[package]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = false
format = "$duration "
style = "bg:lavender"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[nodejs]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[bun]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[c]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[java]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[$symbol $version]($style)'

[python]
symbol = ""
style = "purple"
format = '[$symbol( $version)( #$virtualenv) ]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[$symbol $context]($style)'

[conda]
symbol = ""
style = "bg:sapphire"
format = '[(fg:crust bg:sapphire)]($style)'
ignore_base = false

[lua]
symbol = ""
style = "purple"
format = "[$symbol $context]($style)"
