"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1500

[username]
show_always = true
style_user = "fg:#8AADF5"
format = "[@$user ]($style)"

[directory]
format = "[$path ]($style)"
truncation_length = 6
truncate_to_repo = false
truncation_symbol = "~/"

[git_branch]
style = "fg:yellow"

[git_status]
style = "fg:red"
format = "[$all_status$ahead_behind ]($style)"

[line_break]
disabled = true

[package]
disabled = true

[character]
disabled = false
success_symbol = '[➜](bold fg:green)'
error_symbol = '[](bold fg:red)'

[cmd_duration]
show_milliseconds = false
format = "$duration "
style = "bg:lavender"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[nodejs]
symbol = ""
style = "fg:#339933"
format = '[$symbol $version ]($style)'

[bun]
symbol = ""
style = "fg:#F0DB4F"
format = '[$symbol $version ]($style)'

[c]
symbol = ""
style = "fg:#555555"
format = '[$symbol $version ]($style)'

[rust]
symbol = ""
style = "fg:#DEA584"
format = '[$symbol $version ]($style)'

[golang]
symbol = ""
style = "fg:#00ADD8"
format = '[$symbol $version ]($style)'

[php]
symbol = ""
style = "fg:#777BB4"
format = '[$symbol $version ]($style)'

[java]
symbol = ""
style = "fg:#F89820"
format = '[$symbol $version ]($style)'

[kotlin]
symbol = ""
style = "fg:#7F52FF"
format = '[$symbol $version ]($style)'

[haskell]
symbol = ""
style = "fg:#5e5086"
format = '[$symbol $version ]($style)'

[python]
symbol = ""
style = "fg:#3572A5"
format = '[$symbol( $version)( #$virtualenv) ]($style)'

[docker_context]
symbol = ""
style = "fg:#2496ED"
format = '[$symbol $context ]($style)'

[conda]
symbol = ""
style = "fg:#44A833"
format = '[(fg:crust bg:sapphire) ]($style)'
ignore_base = false

[lua]
symbol = ""
style = "fg:#1993B9"
format = "[$symbol $context ]($style)"
