include colors/colors.conf

font_family JetBrainsMonoNL Nerd Font
disable_ligatures yes
enable_audio_bell no

shell_integration disabled

cursor_shape	block

url_style curly

remember_window_size no
window_padding_width 25
cursor_blink_interval 0

background_opacity 0.8
background_blur 20
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close

sync_to_monitor no

repaint_delay 8
input_delay 3

cursor_trail 3
