name: Update tracked apps table

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-table:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set up python
        uses: actions/setup-python@v7

      - name: Run python script
        run: python ./.github/scripts/update_table.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update table of packages [skip ci]"
          file_pattern: "README.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
